version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code...
      # Add any build commands specific to your application here
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - "**/*"
  discard-paths: no
